# Generated by Django 6.0.2 on 2026-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assessment_assessment_type_assessment_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='academic_year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='num_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='term',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='weeks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
