# Generated by Django 6.0.2 on 2026-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sessionplan_academic_year_sessionplan_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='indicative_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='reflection',
            field=models.TextField(blank=True),
        ),
    ]
