# Generated by Django 6.0.2 on 2026-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessionplan_indicative_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
