# Generated by Django 6.0.2 on 2026-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sessionplan_trainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='cross_cutting_issues',
            field=models.TextField(blank=True, help_text='Gender, Environment, Inclusive education, etc.'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='hse_considerations',
            field=models.TextField(blank=True, help_text='Health, Safety, and Environment considerations'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='ict_tools',
            field=models.TextField(blank=True, help_text='ICT tools used for facilitation'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='performance_criteria',
            field=models.TextField(blank=True, help_text='Specific performance criteria from RTB curriculum'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='pre_requisite_knowledge',
            field=models.TextField(blank=True, help_text='Link to previous lessons or required prior knowledge'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='special_needs_support',
            field=models.TextField(blank=True, help_text='Support for students with special educational needs'),
        ),
    ]
