# Generated by Django 6.0.2 on 2026-02-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sessionplan_cross_cutting_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_recorded',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
