# Generated by Django 6.0.2 on 2026-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemsetting_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='current_term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', help_text='Active academic term. Student promotions are processed during Term 3.', max_length=10),
        ),
    ]
