# Generated by Django 6.0.2 on 2026-05-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_curriculum_learningoutcome_trade_indicativecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='qualification_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
