# Generated by Django 6.0.2 on 2026-05-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_curriculum_qualification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicativecontent',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='syllabusmodule',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(),
        ),
    ]
