# Generated by Django 6.0.2 on 2026-05-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_indicativecontent_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplan',
            name='module',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sessionplan',
            name='topic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sessionplan',
            name='trade',
            field=models.TextField(),
        ),
    ]
