# Generated by Django 6.0.2 on 2026-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_sessionplan_module_alter_sessionplan_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='references',
            field=models.TextField(blank=True, help_text='References and citations'),
        ),
    ]
