# Generated by Django 6.0.2 on 2026-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sessionplan_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='advanced_learners_strategy',
            field=models.TextField(blank=True, help_text='Strategy for advanced learners'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='inclusivity_strategy',
            field=models.TextField(blank=True, help_text='Strategy for inclusivity/accommodations'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='slow_learners_strategy',
            field=models.TextField(blank=True, help_text='Strategy for slow learners'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='student_summary',
            field=models.TextField(blank=True, help_text='A student-friendly simple summary of the session'),
        ),
    ]
