# Generated by Django 6.0.2 on 2026-05-21 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sessionplan_advanced_learners_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='co_teachers',
            field=models.ManyToManyField(blank=True, related_name='co_taught_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(blank=True, help_text='The school/institution name this user belongs to', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='ClassroomShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='core.classroom')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_share_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_share_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'requester')},
            },
        ),
    ]
