# Generated by Django 6.0.2 on 2026-05-25 14:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_classroom_co_teachers_customuser_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='scheme_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='syllabusmodule',
            name='credits',
            field=models.IntegerField(default=10, help_text='Total credits for this module'),
        ),
        migrations.AddField(
            model_name='syllabusmodule',
            name='hours',
            field=models.IntegerField(default=100, help_text='Total learning hours for this module'),
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=150)),
                ('trade', models.CharField(max_length=150)),
                ('qualification_title', models.CharField(blank=True, max_length=200)),
                ('school_year', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('rqf_level', models.CharField(max_length=50)),
                ('trainer_name', models.CharField(max_length=150)),
                ('module_code', models.CharField(max_length=50)),
                ('module_title', models.TextField()),
                ('learning_hours', models.IntegerField(default=100)),
                ('num_classes', models.IntegerField(default=1)),
                ('class_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='core.syllabusmodule')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schemeofworktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeOfWorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(help_text="e.g. '1-2' or '3'", max_length=50)),
                ('learning_outcome', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('indicative_content', models.TextField()),
                ('learning_activities', models.TextField()),
                ('resources', models.TextField()),
                ('formative_assessment', models.TextField()),
                ('learning_place', models.CharField(max_length=150)),
                ('observation', models.TextField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.schemeofwork')),
            ],
        ),
    ]
