# Generated by Django 6.0.2 on 2026-05-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_schemeofworktemplate_syllabusmodule_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofworkweek',
            name='dates',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Sep 1 - Sep 5'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schemeofworkweek',
            name='term',
            field=models.CharField(default='1st Term', help_text="e.g. '1st Term', '2nd Term', '3rd Term'", max_length=50),
        ),
    ]
