# Generated by Django 6.0.2 on 2026-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_schemeofworkweek_dates_schemeofworkweek_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text="Personal Gemini API key (optional). If set, overrides the school's global key for AI features.", max_length=200),
        ),
    ]
