# Generated by Django 6.0.2 on 2026-06-15 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_teacherbreaktime_teachertimetablesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertimetablesettings',
            name='exam_morning_slot',
            field=models.CharField(choices=[('08:30-11:30', '08:30 - 11:30'), ('09:00-12:00', '09:00 - 12:00')], default='09:00-12:00', max_length=20),
        ),
        migrations.AddField(
            model_name='teachertimetablesettings',
            name='state',
            field=models.CharField(choices=[('LEARNING', 'Learning Period'), ('ASSESSMENT', 'Assessment Period'), ('EXAM', 'Final Exam Period')], default='LEARNING', max_length=20),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('MORNING', 'Morning Session'), ('AFTERNOON', 'Afternoon Session')], max_length=20)),
                ('period_type', models.CharField(choices=[('ASSESSMENT', 'Assessment Period'), ('EXAM', 'Final Exam Period')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#4f46e5', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
