# Generated by Django 6.0.2 on 2026-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_teachertimetablesettings_exam_morning_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='session_date',
            field=models.DateField(blank=True, help_text='Date for the session plan', null=True),
        ),
    ]
